### ISSUE TITLE
Release 0.8 not working on Catalina

### ISSUE THREAD

**Issue by xit7** [korseby/TriTag#3]
Hey,

really glad someone picked this up. I used TriTag all the time but now it stopped working (64 bit architecture).

Are you able to release a binary for Catalina please?

I tried my best to compile it on my own, but I am failing (dependency on libid3tag and some other things - I am not a developer).

That would be awesome.

Thanks.

**Comment by korseby** [comment]
Hi @xit7 ,

I gave up on TriTag at the moment as there are too many things that need to be updated. libid3tag used by TriTag is outdated. It even used the old id3 v2.3 format which is obsolete for many years... It would be easier to start all over again from scratch.

I decided that it is easier and faster for me to write a Python script instead. It adds id3 tags to music files by their name and directory name. It is using the naming scheme that I use personally. But it can be easily adapted to your scheme. You can find it here: https://github.com/korseby/py3tag

Feel free to improve TriTag and send pull requests.

Best wishes and a happy new year.

**Comment by xit7** [comment]
Hi @korseby,

awesome, that is of great help. I wrote a few lines using libid3tag and somehow it did the job. But thanks for the pointer to your release. That is very useful! I guess I will be using this from now on.

Although I was using TriTag for many years, I ditch it now because the script runs just fine.

Have a good year as well.

**Comment by korseby** [comment]
Cool. That's really nice.

Can you provide a pull request so that others can benefit from your work?

**Comment by xit7** [comment]
He,

sorry, I think I wasn't clear: I did not alter the code of TriTag (I tried but failed). I just used libid3tag with a quick script I wrote. But that is very custom to my situation.

But I learned (from you) that libid3tag is outdated. So I guess your py3tag is the way to go, at least for me. Will try in the future.

See you!
